service: fb-live-video-webhook

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: python3.7
  stage: {dev, test, prod}
  region: eu-central-1
  timeout: 30
  role: arn:aws:iam::208165541056:role/BI-Data-Engineer-Role
  service: fb-live-video-webhook

functions:
  webhook:
    name: ${self:provider.service}-${self:provider.stage}
    handler: src/lambda_function.webhook
    environment:
      BUCKET: YOUR_BUCKET
      BUCKET_PATH: YOUR_PATH
      STATE: {dev, test, prod}
      VERIFY_TOKEN: YOUR_TOKEN
    events:
      - http: ANY webhook
